import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "ByteChain Academy",
  description: "Generated by create next app",
  icons: {
    icon: "/icons/bytechain.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className=''
      >
        {children}
      </body>
    </html>
  );
}
